name: Build Mac Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install electron-rebuild
      run: npm install --save-dev electron-rebuild
      
    - name: Rebuild native modules
      run: npm run rebuild
      
    - name: Build Mac executable
      run: npm run build-mac
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mac-executables
        path: |
          dist/*.dmg
          dist/*.zip
          dist/*.blockmap
